#!/usr/bin/env python3
"""Capture a single PointCloud2 message and write it to a PLY file.

The PLY (Stanford Polygon) format is read natively by Polyscope and is
trivial to load from numpy in any Python version, so this script is the
hand-off point between the ROS 2 (Python 3.10) sim and the Python 3.12
clustering / Polyscope environment.

Reads parameters from a YAML file passed via --params (the same
sim_params.yaml used to generate the world), so output dir, voxel size
and one-shot mode stay in one place.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import numpy as np
import rclpy
import yaml
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
from sensor_msgs.msg import PointCloud2
from sensor_msgs_py import point_cloud2 as pc2


def expand(p: str) -> str:
    return os.path.expanduser(os.path.expandvars(p))


def voxel_downsample(xyz: np.ndarray, rgb: np.ndarray | None, voxel: float):
    if voxel <= 0.0:
        return xyz, rgb
    keys = np.floor(xyz / voxel).astype(np.int64)
    # Hash 3D integer keys into a single int64 for unique-by-row.
    flat = (keys[:, 0] * 73856093) ^ (keys[:, 1] * 19349663) ^ (keys[:, 2] * 83492791)
    _, idx = np.unique(flat, return_index=True)
    idx.sort()
    return xyz[idx], (rgb[idx] if rgb is not None else None)


def write_ply(path: str, xyz: np.ndarray, rgb: np.ndarray | None) -> None:
    n = xyz.shape[0]
    has_rgb = rgb is not None and rgb.shape[0] == n
    with open(path, "wb") as f:
        header = [
            "ply",
            "format binary_little_endian 1.0",
            f"comment generated by holoassist_sim/save_pointcloud.py at {time.strftime('%Y-%m-%dT%H:%M:%S%z')}",
            f"element vertex {n}",
            "property float x",
            "property float y",
            "property float z",
        ]
        if has_rgb:
            header += [
                "property uchar red",
                "property uchar green",
                "property uchar blue",
            ]
        header.append("end_header")
        f.write(("\n".join(header) + "\n").encode("ascii"))
        if has_rgb:
            buf = np.empty(
                n,
                dtype=[("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
                       ("r", "u1"), ("g", "u1"), ("b", "u1")],
            )
            buf["x"] = xyz[:, 0]
            buf["y"] = xyz[:, 1]
            buf["z"] = xyz[:, 2]
            buf["r"] = rgb[:, 0]
            buf["g"] = rgb[:, 1]
            buf["b"] = rgb[:, 2]
        else:
            buf = np.empty(n, dtype=[("x", "<f4"), ("y", "<f4"), ("z", "<f4")])
            buf["x"] = xyz[:, 0]
            buf["y"] = xyz[:, 1]
            buf["z"] = xyz[:, 2]
        f.write(buf.tobytes())


def unpack_rgb(rgb_field: np.ndarray) -> np.ndarray:
    """ROS convention: rgb packed as float32 (bit-cast from uint32 0x00RRGGBB)."""
    if rgb_field.dtype == np.float32:
        as_u32 = rgb_field.view(np.uint32)
    else:
        as_u32 = rgb_field.astype(np.uint32)
    r = ((as_u32 >> 16) & 0xFF).astype(np.uint8)
    g = ((as_u32 >> 8) & 0xFF).astype(np.uint8)
    b = (as_u32 & 0xFF).astype(np.uint8)
    return np.stack([r, g, b], axis=1)


def _build_base_name(params: dict) -> str:
    """Build a descriptive base filename from sim_params without version suffix.

    Format: <description>_<N>cubes_<size>mm
    Examples:
        default_4cubes_40mm
        spread_4cubes_40mm
        clustered_6cubes_mixed
    """
    cap = params.get("capture", {})
    cubes = params.get("cubes", [])

    desc = cap.get("description", "scene").strip().replace(" ", "_")
    n = len(cubes)

    sizes_mm = []
    for c in cubes:
        s = c.get("size", [0.04, 0.04, 0.04])
        sizes_mm.append(round(max(s) * 1000))

    if len(set(sizes_mm)) == 1:
        size_str = f"{sizes_mm[0]}mm" if sizes_mm else "unknown"
    else:
        size_str = "mixed"

    return f"{desc}_{n}cubes_{size_str}"


def _next_version(output_dir: str, base: str) -> str:
    """Return the next non-existing versioned path: <base>_v001.ply, _v002.ply …"""
    v = 1
    while True:
        candidate = os.path.join(output_dir, f"{base}_v{v:03d}.ply")
        if not os.path.exists(candidate):
            return candidate
        v += 1


class PointCloudSaver(Node):
    def __init__(self, params: dict, override_topic: str | None) -> None:
        super().__init__("pointcloud_saver")

        cap = params.get("capture", {})
        cam = params.get("camera", {})

        self.topic = override_topic or f"{cam.get('topic', '/camera')}/points"
        self.output_dir = expand(cap.get("output_dir", "~/holoassist_pointclouds"))
        self.one_shot = bool(cap.get("one_shot", True))
        self.voxel = float(cap.get("voxel_size", 0.0))
        self.base_name = _build_base_name(params)

        Path(self.output_dir).mkdir(parents=True, exist_ok=True)

        # Gazebo bridge publishes BEST_EFFORT by default for sensor data.
        qos = QoSProfile(
            reliability=ReliabilityPolicy.BEST_EFFORT,
            history=HistoryPolicy.KEEP_LAST,
            depth=5,
        )
        self.sub = self.create_subscription(PointCloud2, self.topic, self.on_cloud, qos)
        self.get_logger().info(
            f"Listening on {self.topic} -> saving to {self.output_dir}/{self.base_name}_vNNN.ply"
            f"  (voxel={self.voxel}, one_shot={self.one_shot})"
        )

    def on_cloud(self, msg: PointCloud2) -> None:
        field_names = [f.name for f in msg.fields]
        wanted = ["x", "y", "z"] + (["rgb"] if "rgb" in field_names else [])
        records = pc2.read_points(msg, field_names=wanted, skip_nans=True)
        records = np.asarray(list(records)) if not isinstance(records, np.ndarray) else records

        if records.size == 0:
            self.get_logger().warn("Received empty cloud, skipping.")
            return

        # Structured array -> plain float32 (N,3)
        xyz = np.stack([records["x"], records["y"], records["z"]], axis=1).astype(np.float32)
        rgb = unpack_rgb(records["rgb"]) if "rgb" in wanted else None

        # Drop residual non-finite rows.
        finite = np.isfinite(xyz).all(axis=1)
        xyz = xyz[finite]
        if rgb is not None:
            rgb = rgb[finite]

        xyz, rgb = voxel_downsample(xyz, rgb, self.voxel)

        out = _next_version(self.output_dir, self.base_name)
        write_ply(out, xyz, rgb)
        self.get_logger().info(
            f"Wrote {out}  ({xyz.shape[0]} points, rgb={'yes' if rgb is not None else 'no'})"
        )

        if self.one_shot:
            self.get_logger().info("one_shot=true, shutting down.")
            rclpy.shutdown()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--params", required=True, help="path to sim_params.yaml")
    parser.add_argument("--topic", default=None, help="override input topic")
    args, ros_args = parser.parse_known_args()

    with open(args.params, "r") as f:
        params = yaml.safe_load(f)

    rclpy.init(args=ros_args)
    node = PointCloudSaver(params, args.topic)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        if rclpy.ok():
            rclpy.shutdown()
    return 0


if __name__ == "__main__":
    sys.exit(main())
